export const BASE_URL = "http://localhost:8080/";

// LOGIN PAGE :
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

// ALERT POPUP :
export const SHOW_INFO_ALERT = 'SHOW_INFO_ALERT';
export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
export const SHOW_WARNING_ALERT = 'SHOW_WARNING_ALERT';
export const SHOW_SUCCESS_ALERT = 'SHOW_SUCCESS_ALERT';

// USER CREATE DIALOG:
export const SHOW_CREATE_USER_DIALOG  = 'SHOW_CREATE_USER_DIALOG';
export const HIDE_CREATE_USER_DIALOG  = 'HIDE_CREATE_USER_DIALOG';

// CONFIRMATION DIALOG :
export const SHOW_CONFIRMATION_DIALOG = 'SHOW_CONFIRMATION_DIALOG';
export const HIDE_CONFIRMATION_DIALOG = 'HIDE_CONFIRMATION_DIALOG';